<a href="https://colab.research.google.com/github/priyansh-commits/practice/blob/main/hyperparamter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')
df.head()
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64
 9   tax      506 non-null    int64
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

In [8]:
df.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
from sklearn.model_selection import cross_val_score,KFold
from sklearn.neighbors import KNeighborsRegressor

In [12]:
knn=KNeighborsRegressor()
kfold = KFold(n_splits=5, shuffle=True, random_state=1)
scores = cross_val_score(knn, X, y, cv=kfold, scoring='r2')
scores.mean()

np.float64(0.4761976351913221)

In [16]:
param_grid={'weights':['uniform','distance'],
            'algorithm':['ball_tree', 'kd_tree', 'brute'],
            'p':[1,2],
            'n_neighbors':[1,3,5,7,9,11]
            }

In [22]:
from sklearn.model_selection import GridSearchCV
gc=GridSearchCV(estimator=knn,param_grid=param_grid,scoring='r2', n_jobs=-1, refit=True, cv=kfold, verbose=0, pre_dispatch='2*n_jobs',  return_train_score=False)

In [23]:
gc.fit(X,y)

GridSearchCV(cv=KFold(n_splits=5, random_state=1, shuffle=True),
             estimator=KNeighborsRegressor(), n_jobs=-1,
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1, 3, 5, 7, 9, 11], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='r2')

In [24]:
print(gc.best_params_)
print(gc.best_score_)

{'algorithm': 'ball_tree', 'n_neighbors': 5, 'p': 1, 'weights': 'distance'}
0.6117139367845081

In [27]:
pd.DataFrame(gc.cv_results_)[['param_algorithm',	'param_n_neighbors',	'param_p', 'param_weights', 'mean_test_score']].sort_values('mean_test_score',ascending=False).head(10)

   param_algorithm  param_n_neighbors  param_p param_weights  mean_test_score
33         kd_tree                  5        1      distance         0.611714
57           brute                  5        1      distance         0.611714
9        ball_tree                  5        1      distance         0.611714
37         kd_tree                  7        1      distance         0.605716
13       ball_tree                  7        1      distance         0.605716
61           brute                  7        1      distance         0.605716
32         kd_tree                  5        1       uniform         0.589759
8        ball_tree                  5        1       uniform         0.589759
56           brute                  5        1       uniform         0.589759
41         kd_tree                  9        1      distance         0.586899

In [30]:
from sklearn.model_selection import RandomizedSearchCV
rv=RandomizedSearchCV(estimator=knn,param_distributions=param_grid,scoring='r2', n_jobs=-1, refit=True, cv=kfold, verbose=0, pre_dispatch='2*n_jobs',  return_train_score=False)

In [31]:
rv.fit(X,y)

RandomizedSearchCV(cv=KFold(n_splits=5, random_state=1, shuffle=True),
                   estimator=KNeighborsRegressor(), n_jobs=-1,
                   param_distributions={'algorithm': ['ball_tree', 'kd_tree',
                                                      'brute'],
                                        'n_neighbors': [1, 3, 5, 7, 9, 11],
                                        'p': [1, 2],
                                        'weights': ['uniform', 'distance']},
                   scoring='r2')

In [33]:
rv.best_params_

{'weights': 'distance', 'p': 1, 'n_neighbors': 5, 'algorithm': 'ball_tree'}

In [36]:
rv.best_score_

np.float64(0.6117139367845081)