<a href="https://colab.research.google.com/github/priyansh-commits/practice/blob/main/naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv('/content/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
pd.crosstab(df.Pclass,df.Survived,margins=True,normalize='all')

Survived         0         1       All
Pclass
1         0.089787  0.152637  0.242424
2         0.108866  0.097643  0.206510
3         0.417508  0.133558  0.551066
All       0.616162  0.383838  1.000000

In [11]:
import numpy as np
import pandas as pd
df = pd.read_csv('https://gist.githubusercontent.com/DiogoRibeiro7/c6590d0cf119e87c39e31c21a9c0f3a8/raw/4a8e3da267a0c1f0d650901d8295a5153bde8b21/PlayTennis.csv')
df.head()
print(pd.crosstab(df.Outlook,df['Play Tennis'],normalize='columns'))
print('          ')
print(pd.crosstab(df.Temperature,df['Play Tennis'],normalize='columns'))
print('          ')
print(pd.crosstab(df.Humidity,df['Play Tennis'],normalize='columns'))
print('          ')
print(pd.crosstab(df.Wind,df['Play Tennis'],normalize='columns'))

Play Tennis   No       Yes
Outlook
Overcast     0.0  0.444444
Rain         0.4  0.333333
Sunny        0.6  0.222222

Play Tennis   No       Yes
Temperature
Cool         0.2  0.333333
Hot          0.4  0.222222
Mild         0.4  0.444444

Play Tennis   No       Yes
Humidity
High         0.8  0.333333
Normal       0.2  0.666667

Play Tennis   No       Yes
Wind
Strong       0.6  0.333333
Weak         0.4  0.666667

In [8]:
df['Play Tennis'].value_counts()

Play Tennis
Yes    9
No     5
Name: count, dtype: int64

In [13]:
D = {}
for i in ['Outlook','Temperature',	'Humidity',	'Wind']:
  D.update(pd.crosstab(df[i], df['Play Tennis'],normalize='columns').stack().to_dict())
D

{('Overcast', 'No'): 0.0,
 ('Overcast', 'Yes'): 0.4444444444444444,
 ('Rain', 'No'): 0.4,
 ('Rain', 'Yes'): 0.3333333333333333,
 ('Sunny', 'No'): 0.6,
 ('Sunny', 'Yes'): 0.2222222222222222,
 ('Cool', 'No'): 0.2,
 ('Cool', 'Yes'): 0.3333333333333333,
 ('Hot', 'No'): 0.4,
 ('Hot', 'Yes'): 0.2222222222222222,
 ('Mild', 'No'): 0.4,
 ('Mild', 'Yes'): 0.4444444444444444,
 ('High', 'No'): 0.8,
 ('High', 'Yes'): 0.3333333333333333,
 ('Normal', 'No'): 0.2,
 ('Normal', 'Yes'): 0.6666666666666666,
 ('Strong', 'No'): 0.6,
 ('Strong', 'Yes'): 0.3333333333333333,
 ('Weak', 'No'): 0.4,
 ('Weak', 'Yes'): 0.6666666666666666}