<a href="https://colab.research.google.com/github/priyansh-commits/practice/blob/main/session_18_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
pd.options.display.max_columns = None
# to show all the records, use the below code
# pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [2]:
# To get the details about the dataset, please visit
# https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
df = pd.read_csv(url)
df.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [29]:
d={}
for i in df['Team'].unique():
  d[i]=round((df[df['Team']==i]['On Target'].sum()/df[df['Team']==i]['Total Attempts'].sum())*100,2)
d = dict(sorted(d.items(), key=lambda item: item[1] ,reverse=True))
print(d)

{'Costa Rica': np.float64(54.55), 'Cameroon': np.float64(51.85), 'Ecuador': np.float64(48.15), 'Argentina': np.float64(46.15), 'Brazil': np.float64(45.56), 'England': np.float64(45.0), 'Portugal': np.float64(40.32), 'Ghana': np.float64(40.0), 'Netherlands': np.float64(39.02), 'Korea Republic': np.float64(36.73), 'Australia': np.float64(36.0), 'Mexico': np.float64(34.88), 'France': np.float64(34.65), 'Germany': np.float64(34.33), 'Croatia': np.float64(33.73), 'Spain': np.float64(32.69), 'Belgium': np.float64(32.35), 'Serbia': np.float64(32.26), 'Iran': np.float64(31.43), 'Uruguay': np.float64(31.25), 'United States': np.float64(31.11), 'Saudi Arabia': np.float64(31.03), 'Senegal': np.float64(30.77), 'Denmark': np.float64(30.56), 'Switzerland': np.float64(30.56), 'Japan': np.float64(30.23), 'Wales': np.float64(29.17), 'Qatar': np.float64(28.57), 'Morocco': np.float64(28.33), 'Tunisia': np.float64(26.67), 'Poland': np.float64(25.0), 'Canada': np.float64(17.65)}

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [45]:
team_rank=df.groupby('Team')['Pts'].sum().sort_values(ascending=False).rank(method='first')
df['rank'] = df['Team'].map(team_rank)
df.sort_values('rank')

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts,percent,rank
23,24,12,Canada,Belgium,F,0,43,0,0,0,21,4,12,16,5,17,6,8,5,20,117,15,176,123,23,13,2,0,14,1,448,382,19,6,4,10,0,0,19.0,1.0
53,54,27,Canada,Croatia,F,1,45,1,0,1,8,2,3,1,7,8,4,3,4,13,46,5,102,70,2,1,2,0,5,3,514,440,18,5,2,14,0,0,25.0,1.0
82,83,42,Canada,Morocco,F,1,45,0,0,0,5,0,4,4,1,22,4,2,6,11,75,9,152,89,9,6,4,0,14,4,536,476,24,6,6,18,0,0,0.0,1.0
34,35,18,Qatar,Senegal,A,1,42,1,0,1,10,2,7,4,6,7,5,2,5,11,79,9,174,117,13,7,3,0,7,4,424,353,18,5,6,15,0,0,20.0,2.0
65,66,33,Qatar,Netherlands,A,0,36,0,0,0,6,4,2,2,4,10,7,5,4,6,86,6,163,116,7,5,0,0,0,0,457,394,18,4,2,24,0,0,67.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,78,39,Argentina,Poland,C,2,67,1,1,2,25,13,8,10,15,25,8,7,10,26,150,36,141,126,20,16,1,0,11,0,862,814,22,5,9,5,0,3,52.0,32.0
98,99,50,Argentina,Australia,C,2,53,2,0,1,14,5,7,11,3,15,6,11,2,17,127,8,181,135,16,8,0,0,8,4,711,635,6,1,1,15,0,3,36.0,32.0
115,116,58,Argentina,Netherlands,C,2,44,2,0,1,15,6,8,5,10,7,7,13,6,17,104,7,203,122,24,8,8,0,18,2,603,511,16,4,8,30,5,3,40.0,32.0
120,121,61,Argentina,Croatia,C,3,34,3,0,1,10,7,2,7,3,8,9,7,3,2,121,7,147,91,17,7,2,0,15,1,408,344,8,2,2,6,1,3,70.0,32.0
126,127,64,Argentina,France,C,3,46,3,0,1,21,9,9,13,8,13,6,8,9,9,163,28,249,172,40,24,4,0,26,4,648,544,20,4,6,22,5,3,43.0,32.0

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [52]:
# df.drop('SlNo',axis=1,inplace=True)
df.drop('Match No.',axis=1,inplace=True)
df.drop('Red Cards',axis=1,inplace=True)
df.drop('Pts',axis=1,inplace=True)

###`Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [53]:
df['rank'].astype(np.int16)
df.set_index('rank',inplace=True)
df.sort_index()

,Sl. No,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,percent
rank,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1.0,24,Canada,Belgium,F,0,43,0,0,0,21,4,12,16,5,17,6,8,5,20,117,15,176,123,23,13,2,14,1,448,382,19,6,4,10,0,19.0
1.0,54,Canada,Croatia,F,1,45,1,0,1,8,2,3,1,7,8,4,3,4,13,46,5,102,70,2,1,2,5,3,514,440,18,5,2,14,0,25.0
1.0,83,Canada,Morocco,F,1,45,0,0,0,5,0,4,4,1,22,4,2,6,11,75,9,152,89,9,6,4,14,4,536,476,24,6,6,18,0,0.0
2.0,35,Qatar,Senegal,A,1,42,1,0,1,10,2,7,4,6,7,5,2,5,11,79,9,174,117,13,7,3,7,4,424,353,18,5,6,15,0,20.0
2.0,66,Qatar,Netherlands,A,0,36,0,0,0,6,4,2,2,4,10,7,5,4,6,86,6,163,116,7,5,0,0,0,457,394,18,4,2,24,0,67.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32.0,78,Argentina,Poland,C,2,67,1,1,2,25,13,8,10,15,25,8,7,10,26,150,36,141,126,20,16,1,11,0,862,814,22,5,9,5,0,52.0
32.0,99,Argentina,Australia,C,2,53,2,0,1,14,5,7,11,3,15,6,11,2,17,127,8,181,135,16,8,0,8,4,711,635,6,1,1,15,0,36.0
32.0,116,Argentina,Netherlands,C,2,44,2,0,1,15,6,8,5,10,7,7,13,6,17,104,7,203,122,24,8,8,18,2,603,511,16,4,8,30,5,40.0
32.0,121,Argentina,Croatia,C,3,34,3,0,1,10,7,2,7,3,8,9,7,3,2,121,7,147,91,17,7,2,15,1,408,344,8,2,2,6,1,70.0
32.0,127,Argentina,France,C,3,46,3,0,1,21,9,9,13,8,13,6,8,9,9,163,28,249,172,40,24,4,26,4,648,544,20,4,6,22,5,43.0

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

## Questions on IPL wala dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

###`Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [65]:
ipl = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv")
ipl.replace('Delhi Daredevils','Delhi Capitals',inplace=True)
ipl.replace('Kings XI Punjab','Punjab Kings',inplace=True)
ipl.replace('Rising Pune Supergiants','Rising Pune Supergiant',inplace=True)
match=ipl['Team1'].value_counts()+ipl['Team2'].value_counts()
for i in ipl['Team1'].unique():

     ID City Date Season MatchNumber Team1 Team2 Venue TossWinner  \
0   NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
1   NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
3   NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
6   NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
11  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
..   ..  ...  ...    ...         ...   ...   ...   ...        ...
931 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
939 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
941 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
944 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
947 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN

    TossDecision SuperOver WinningTeam WonBy  Margin method Player_of_Match  \
0            NaN       NaN         NaN   NaN     NaN    NaN             NaN
1            NaN       NaN         NaN   NaN     NaN    NaN             NaN
3            NaN       NaN         NaN   NaN     NaN    NaN             NaN
6            NaN       NaN         NaN   NaN     NaN    NaN             NaN
11           NaN       NaN         NaN   NaN     NaN    NaN             NaN
..           ...       ...         ...   ...     ...    ...             ...
931          NaN       NaN         NaN   NaN     NaN    NaN             NaN
939          NaN       NaN         NaN   NaN     NaN    NaN             NaN
941          NaN       NaN         NaN   NaN     NaN    NaN             NaN
944          NaN       NaN         NaN   NaN     NaN    NaN             NaN
947          NaN       NaN         NaN   NaN     NaN    NaN             NaN

    Team1Players Team2Players Umpire1 Umpire2
0            NaN          NaN     NaN     NaN
1            NaN          NaN     NaN     NaN
3            NaN          NaN     NaN     NaN
6            NaN          NaN     NaN     NaN
11           NaN          NaN     NaN     NaN
..           ...          ...     ...     ...
931          NaN          NaN     NaN     NaN
939          NaN          NaN     NaN     NaN
941          NaN          NaN     NaN     NaN
944          NaN          NaN     NaN     NaN
947          NaN          NaN     NaN     NaN

[192 rows x 20 columns]
     ID City Date Season MatchNumber Team1 Team2 Venue TossWinner  \
1   NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
2   NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
7   NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
14  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
20  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
..   ..  ...  ...    ...         ...   ...   ...   ...        ...
933 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
935 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
939 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
946 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
949 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN

    TossDecision SuperOver WinningTeam WonBy  Margin method Player_of_Match  \
1            NaN       NaN         NaN   NaN     NaN    NaN             NaN
2            NaN       NaN         NaN   NaN     NaN    NaN             NaN
7            NaN       NaN         NaN   NaN     NaN    NaN             NaN
14           NaN       NaN         NaN   NaN     NaN    NaN             NaN
20           NaN       NaN         NaN   NaN     NaN    NaN             NaN
..           ...       ...         ...   ...     ...    ...             ...
933          NaN       NaN         NaN   NaN     NaN    NaN             NaN
935          NaN       NaN         NaN   NaN     NaN    NaN             NaN
939          NaN       NaN         NaN   NaN     NaN    NaN             NaN
946          NaN       NaN         NaN   NaN     NaN    NaN             NaN
949          NaN       NaN         NaN   NaN     NaN    NaN             NaN

    Team1Players Team2Players Umpire1 Umpire2
1            NaN          NaN     NaN     NaN
2            NaN          NaN     NaN     NaN
7            NaN          NaN     NaN     NaN
14           NaN          NaN     NaN     NaN
20           NaN          NaN     NaN     NaN
..           ...          ...     ...     ...
933          NaN          NaN     NaN     NaN
935          NaN          NaN     NaN     NaN
939          NaN          NaN     NaN     NaN
946          NaN          NaN     NaN     NaN
949          NaN          NaN     NaN     NaN

[226 rows x 20 columns]
     ID City Date Season MatchNumber Team1 Team2 Venue TossWinner  \
4   NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
9   NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
13  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
20  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
24  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
..   ..  ...  ...    ...         ...   ...   ...   ...        ...
611 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
614 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
618 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
621 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
625 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN

    TossDecision SuperOver WinningTeam WonBy  Margin method Player_of_Match  \
4            NaN       NaN         NaN   NaN     NaN    NaN             NaN
9            NaN       NaN         NaN   NaN     NaN    NaN             NaN
13           NaN       NaN         NaN   NaN     NaN    NaN             NaN
20           NaN       NaN         NaN   NaN     NaN    NaN             NaN
24           NaN       NaN         NaN   NaN     NaN    NaN             NaN
..           ...       ...         ...   ...     ...    ...             ...
611          NaN       NaN         NaN   NaN     NaN    NaN             NaN
614          NaN       NaN         NaN   NaN     NaN    NaN             NaN
618          NaN       NaN         NaN   NaN     NaN    NaN             NaN
621          NaN       NaN         NaN   NaN     NaN    NaN             NaN
625          NaN       NaN         NaN   NaN     NaN    NaN             NaN

    Team1Players Team2Players Umpire1 Umpire2
4            NaN          NaN     NaN     NaN
9            NaN          NaN     NaN     NaN
13           NaN          NaN     NaN     NaN
20           NaN          NaN     NaN     NaN
24           NaN          NaN     NaN     NaN
..           ...          ...     ...     ...
611          NaN          NaN     NaN     NaN
614          NaN          NaN     NaN     NaN
618          NaN          NaN     NaN     NaN
621          NaN          NaN     NaN     NaN
625          NaN          NaN     NaN     NaN

[152 rows x 20 columns]
     ID City Date Season MatchNumber Team1 Team2 Venue TossWinner  \
5   NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
10  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
16  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
19  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
24  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
..   ..  ...  ...    ...         ...   ...   ...   ...        ...
930 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
933 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
936 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
943 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
947 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN

    TossDecision SuperOver WinningTeam WonBy  Margin method Player_of_Match  \
5            NaN       NaN         NaN   NaN     NaN    NaN             NaN
10           NaN       NaN         NaN   NaN     NaN    NaN             NaN
16           NaN       NaN         NaN   NaN     NaN    NaN             NaN
19           NaN       NaN         NaN   NaN     NaN    NaN             NaN
24           NaN       NaN         NaN   NaN     NaN    NaN             NaN
..           ...       ...         ...   ...     ...    ...             ...
930          NaN       NaN         NaN   NaN     NaN    NaN             NaN
933          NaN       NaN         NaN   NaN     NaN    NaN             NaN
936          NaN       NaN         NaN   NaN     NaN    NaN             NaN
943          NaN       NaN         NaN   NaN     NaN    NaN             NaN
947          NaN       NaN         NaN   NaN     NaN    NaN             NaN

    Team1Players Team2Players Umpire1 Umpire2
5            NaN          NaN     NaN     NaN
10           NaN          NaN     NaN     NaN
16           NaN          NaN     NaN     NaN
19           NaN          NaN     NaN     NaN
24           NaN          NaN     NaN     NaN
..           ...          ...     ...     ...
930          NaN          NaN     NaN     NaN
933          NaN          NaN     NaN     NaN
936          NaN          NaN     NaN     NaN
943          NaN          NaN     NaN     NaN
947          NaN          NaN     NaN     NaN

[224 rows x 20 columns]
     ID City Date Season MatchNumber Team1 Team2 Venue TossWinner  \
6   NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
12  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
15  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
19  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
25  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
..   ..  ...  ...    ...         ...   ...   ...   ...        ...
930 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
935 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
938 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
942 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
948 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN

    TossDecision SuperOver WinningTeam WonBy  Margin method Player_of_Match  \
6            NaN       NaN         NaN   NaN     NaN    NaN             NaN
12           NaN       NaN         NaN   NaN     NaN    NaN             NaN
15           NaN       NaN         NaN   NaN     NaN    NaN             NaN
19           NaN       NaN         NaN   NaN     NaN    NaN             NaN
25           NaN       NaN         NaN   NaN     NaN    NaN             NaN
..           ...       ...         ...   ...     ...    ...             ...
930          NaN       NaN         NaN   NaN     NaN    NaN             NaN
935          NaN       NaN         NaN   NaN     NaN    NaN             NaN
938          NaN       NaN         NaN   NaN     NaN    NaN             NaN
942          NaN       NaN         NaN   NaN     NaN    NaN             NaN
948          NaN       NaN         NaN   NaN     NaN    NaN             NaN

    Team1Players Team2Players Umpire1 Umpire2
6            NaN          NaN     NaN     NaN
12           NaN          NaN     NaN     NaN
15           NaN          NaN     NaN     NaN
19           NaN          NaN     NaN     NaN
25           NaN          NaN     NaN     NaN
..           ...          ...     ...     ...
930          NaN          NaN     NaN     NaN
935          NaN          NaN     NaN     NaN
938          NaN          NaN     NaN     NaN
942          NaN          NaN     NaN     NaN
948          NaN          NaN     NaN     NaN

[208 rows x 20 columns]
    ID City Date Season MatchNumber Team1 Team2 Venue TossWinner TossDecision  \
0  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
3  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
7  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
12 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
17 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
23 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
26 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
31 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
34 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
39 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
45 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
50 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
53 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
58 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
64 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
70 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN

   SuperOver WinningTeam WonBy  Margin method Player_of_Match Team1Players  \
0        NaN         NaN   NaN     NaN    NaN             NaN          NaN
3        NaN         NaN   NaN     NaN    NaN             NaN          NaN
7        NaN         NaN   NaN     NaN    NaN             NaN          NaN
12       NaN         NaN   NaN     NaN    NaN             NaN          NaN
17       NaN         NaN   NaN     NaN    NaN             NaN          NaN
23       NaN         NaN   NaN     NaN    NaN             NaN          NaN
26       NaN         NaN   NaN     NaN    NaN             NaN          NaN
31       NaN         NaN   NaN     NaN    NaN             NaN          NaN
34       NaN         NaN   NaN     NaN    NaN             NaN          NaN
39       NaN         NaN   NaN     NaN    NaN             NaN          NaN
45       NaN         NaN   NaN     NaN    NaN             NaN          NaN
50       NaN         NaN   NaN     NaN    NaN             NaN          NaN
53       NaN         NaN   NaN     NaN    NaN             NaN          NaN
58       NaN         NaN   NaN     NaN    NaN             NaN          NaN
64       NaN         NaN   NaN     NaN    NaN             NaN          NaN
70       NaN         NaN   NaN     NaN    NaN             NaN          NaN

   Team2Players Umpire1 Umpire2
0           NaN     NaN     NaN
3           NaN     NaN     NaN
7           NaN     NaN     NaN
12          NaN     NaN     NaN
17          NaN     NaN     NaN
23          NaN     NaN     NaN
26          NaN     NaN     NaN
31          NaN     NaN     NaN
34          NaN     NaN     NaN
39          NaN     NaN     NaN
45          NaN     NaN     NaN
50          NaN     NaN     NaN
53          NaN     NaN     NaN
58          NaN     NaN     NaN
64          NaN     NaN     NaN
70          NaN     NaN     NaN
    ID City Date Season MatchNumber Team1 Team2 Venue TossWinner TossDecision  \
2  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
8  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
11 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
17 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
21 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
29 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
32 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
37 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
43 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
48 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
54 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
59 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
62 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
67 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN
70 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN          NaN

   SuperOver WinningTeam WonBy  Margin method Player_of_Match Team1Players  \
2        NaN         NaN   NaN     NaN    NaN             NaN          NaN
8        NaN         NaN   NaN     NaN    NaN             NaN          NaN
11       NaN         NaN   NaN     NaN    NaN             NaN          NaN
17       NaN         NaN   NaN     NaN    NaN             NaN          NaN
21       NaN         NaN   NaN     NaN    NaN             NaN          NaN
29       NaN         NaN   NaN     NaN    NaN             NaN          NaN
32       NaN         NaN   NaN     NaN    NaN             NaN          NaN
37       NaN         NaN   NaN     NaN    NaN             NaN          NaN
43       NaN         NaN   NaN     NaN    NaN             NaN          NaN
48       NaN         NaN   NaN     NaN    NaN             NaN          NaN
54       NaN         NaN   NaN     NaN    NaN             NaN          NaN
59       NaN         NaN   NaN     NaN    NaN             NaN          NaN
62       NaN         NaN   NaN     NaN    NaN             NaN          NaN
67       NaN         NaN   NaN     NaN    NaN             NaN          NaN
70       NaN         NaN   NaN     NaN    NaN             NaN          NaN

   Team2Players Umpire1 Umpire2
2           NaN     NaN     NaN
8           NaN     NaN     NaN
11          NaN     NaN     NaN
17          NaN     NaN     NaN
21          NaN     NaN     NaN
29          NaN     NaN     NaN
32          NaN     NaN     NaN
37          NaN     NaN     NaN
43          NaN     NaN     NaN
48          NaN     NaN     NaN
54          NaN     NaN     NaN
59          NaN     NaN     NaN
62          NaN     NaN     NaN
67          NaN     NaN     NaN
70          NaN     NaN     NaN
     ID City Date Season MatchNumber Team1 Team2 Venue TossWinner  \
8   NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
13  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
18  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
21  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
27  NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
..   ..  ...  ...    ...         ...   ...   ...   ...        ...
931 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
934 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
938 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
945 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN
949 NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN

    TossDecision SuperOver WinningTeam WonBy  Margin method Player_of_Match  \
8            NaN       NaN         NaN   NaN     NaN    NaN             NaN
13           NaN       NaN         NaN   NaN     NaN    NaN             NaN
18           NaN       NaN         NaN   NaN     NaN    NaN             NaN
21           NaN       NaN         NaN   NaN     NaN    NaN             NaN
27           NaN       NaN         NaN   NaN     NaN    NaN             NaN
..           ...       ...         ...   ...     ...    ...             ...
931          NaN       NaN         NaN   NaN     NaN    NaN             NaN
934          NaN       NaN         NaN   NaN     NaN    NaN             NaN
938          NaN       NaN         NaN   NaN     NaN    NaN             NaN
945          NaN       NaN         NaN   NaN     NaN    NaN             NaN
949          NaN       NaN         NaN   NaN     NaN    NaN             NaN

    Team1Players Team2Players Umpire1 Umpire2
8            NaN          NaN     NaN     NaN
13           NaN          NaN     NaN     NaN
18           NaN          NaN     NaN     NaN
21           NaN          NaN     NaN     NaN
27           NaN          NaN     NaN     NaN
..           ...          ...     ...     ...
931          NaN          NaN     NaN     NaN
934          NaN          NaN     NaN     NaN
938          NaN          NaN     NaN     NaN
945          NaN          NaN     NaN     NaN
949          NaN          NaN     NaN     NaN

[223 rows x 20 columns]
     ID City Date Season MatchNumber Team1 Team2 Venue TossWinner  \
4   NaN  NaN  NaN    NaN         NaN   NaN   NaN   NaN        NaN

###`Q-7:` Venues with most "no result" matches.

In [ ]:
# code here

###`Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

In [ ]:
# code here

###`Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;
For loosing - 0 Point
For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

In [ ]:
# code here

###`Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.

Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [ ]:
# code here