<a href="https://colab.research.google.com/github/priyansh-commits/practice/blob/main/Task_55_Feature_Selection_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## `Task` Select best features from from Wine Quality dataset.

* Data Link : https://www.kaggle.com/datasets/rajyellow46/wine-quality

* Drive link : https://docs.google.com/spreadsheets/d/e/2PACX-1vQDVwxneOKOaJL13QMhkAhYrgWlH1tICY7RacUnj_lL8m9uUWaaUf3p7bScNyh_D2Rvt7nc1q11adSy/pub?gid=647503637&single=true&output=csv

Note : Follow approach from Feature Selection Session - 2

In [30]:
# Your Code goes Here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from mlxtend.feature_selection import ExhaustiveFeatureSelector as EFS
df=pd.read_csv('/content/winequalityN - winequalityN.csv')
df.sample(5)

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
5473,red,12.3,0.27,0.49,3.1,0.079,28.0,46.0,0.99930,3.20,0.80,10.2,6
3091,white,6.3,0.28,0.47,11.2,0.040,61.0,183.0,0.99592,3.12,0.51,9.5,6
1922,white,7.0,0.12,0.19,4.9,0.055,27.0,127.0,0.99530,3.29,0.41,9.4,5
3995,white,8.0,0.37,0.31,4.7,0.038,3.0,127.0,0.99186,2.90,0.72,12.1,5
2757,white,5.6,0.12,0.26,4.3,0.038,18.0,97.0,0.99477,3.36,0.46,9.2,5

In [29]:
df['type'].value_counts()

type
white    4898
red      1599
Name: count, dtype: int64

In [51]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
y = le.fit_transform(df["type"])   # red=0, white=1
X = df.drop("type", axis=1)
X.fillna(X.mean(), inplace=True)
from sklearn.linear_model import LogisticRegression
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression()
efs1 = EFS(model,
           min_features=1,
           max_features=12,
           scoring='accuracy',
           print_progress=True,
           n_jobs=-1,
           cv=5)
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
sel=efs1.fit(X_train, y_train)
sel.best_idx_
X_train_new=sel.transform(X_train)
X_test_new=sel.transform(X_test)

Features: 4095/4095

In [52]:
model.fit(X_train_new, y_train)
y_pred_train = model.predict(X_train_new)
y_pred_test = model.predict(X_test_new)
from sklearn.metrics import accuracy_score

print("Train Accuracy:", accuracy_score(y_train, y_pred_train))
print("Test Accuracy:", accuracy_score(y_test, y_pred_test))
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_test))

Train Accuracy: 0.9948046950163556
Test Accuracy: 0.9915384615384616
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       314
           1       0.99      0.99      0.99       986

    accuracy                           0.99      1300
   macro avg       0.99      0.99      0.99      1300
weighted avg       0.99      0.99      0.99      1300

In [46]:
# linear reg ofr wine dataset
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

df=pd.read_csv('/content/winequalityN - winequalityN.csv')
df.sample(5)
y = df["quality"]
X = pd.get_dummies(df.drop("quality", axis=1), columns=["type"], drop_first=True)
X.fillna(X.mean(), inplace=True)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
from mlxtend.feature_selection import SequentialFeatureSelector as SFS

sfs1 = SFS(lr,
           k_features=(1, X_train.shape[1]),
           forward=True,
           floating=False,
           verbose=2,
           scoring='r2',
           cv=10)

sel = sfs1.fit(X_train, y_train)
X_train_new = sel.transform(X_train)
X_test_new = sel.transform(X_test)
lr.fit(X_train_new, y_train)
train_pred = lr.predict(X_train_new)
test_pred = lr.predict(X_test_new)
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

print("Train R² :", r2_score(y_train, train_pred))
print("Test R²  :", r2_score(y_test, test_pred))

print("MAE :", mean_absolute_error(y_test, test_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, test_pred)))

[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.8s finished

[2026-07-25 23:08:53] Features: 1/12 -- score: 0.18735608726850622[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    0.9s finished

[2026-07-25 23:08:54] Features: 2/12 -- score: 0.24564557874726015[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.7s finished

[2026-07-25 23:08:54] Features: 3/12 -- score: 0.2561996054091125[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    0.7s finished

[2026-07-25 23:08:55] Features: 4/12 -- score: 0.2655206457605152[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    1.2s finished

[2026-07-25 23:08:56] Features: 5/12 -- score: 0.26949766717812046[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    2.9s finished

[2026-07-25 23:08:59] Features: 6/12 -- score: 0.2728862282343436[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    0.9s finished

[2026-07-25 23:09:00] Features: 7/12 -- score: 0.2741789798300517[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.7s finished

[2026-07-25 23:09:01] Features: 8/12 -- score: 0.2772071490545518[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    1.2s finished

[2026-07-25 23:09:02] Features: 9/12 -- score: 0.2777147948545758[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.5s finished

[2026-07-25 23:09:03] Features: 10/12 -- score: 0.2779054049107647

Train R² : 0.28595087290495347
Test R²  : 0.3403036766719939
MAE : 0.5453974055211317
RMSE: 0.6866953775598061

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.5s finished

[2026-07-25 23:09:03] Features: 11/12 -- score: 0.2800811799825865[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s finished

[2026-07-25 23:09:03] Features: 12/12 -- score: 0.2796967059605716

In [49]:
print("Selected Features:")
print(sel.k_feature_names_)
print(len(sel.k_feature_names_))

print("CV Score:")
print(sel.k_score_)
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

lr = LinearRegression()

# All features
lr.fit(X_train, y_train)
pred = lr.predict(X_test)

print("All Features R²:", r2_score(y_test, pred))

Selected Features:
('fixed acidity', 'volatile acidity', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'type_white')
11
CV Score:
0.2800811799825865
All Features R²: 0.34048454089868563

In [50]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

lr = LinearRegression()

# Selected features
lr.fit(X_train_new, y_train)
pred_sel = lr.predict(X_test_new)

# All features
lr.fit(X_train, y_train)
pred_all = lr.predict(X_test)

print("Selected Features Test R² :", r2_score(y_test, pred_sel))
print("All Features Test R²      :", r2_score(y_test, pred_all))

Selected Features Test R² : 0.3403036766719939
All Features Test R²      : 0.34048454089868563